class Configs:
    FOOD_CAPACITY_MAX = 20
    FOOD_CAPACITY_MIN = 5
    SEARCH_REGION_HEIGHT = 1000
    SEARCH_REGION_WIDTH = 1000
    COLONY_SIZE = 50
    DIMENSION = 2
    EMPLOYED_AGENTS = int(COLONY_SIZE/2)
    ONLOOKER_AGENTS = COLONY_SIZE - EMPLOYED_AGENTS
    SOURCES = 250